### PR TITLE
Prolog state

### PR DESCRIPTION
**Pull request by cehteh**
more on prolog_state passing, removing q->cycle_error from print.c, fixing some leaks

### CODE REVIEW

**Comment by infradig** [comment]
Looks good. I'll try it out.

Re: q->s_mask & q->nv_start, i'm curious why you'd think they would represent a potential reentrancy issue. A query object represents a thread of execution (concurrency) for a ?- goal. Even if pre-emptive threads were introduced, a physical thread would just be swapping query ptrs like the current cooperative model. It would not be possible for 2+ threads to ever access the same query object concurrently. Other objects would need protection (especially global ones like the literal pool).

**Comment by infradig** [comment]
Or maybe reentrant from the point of view of embedded goals like findall/bagof/setof. Maybe.

**Comment by cehteh** [comment]
On 2020-12-08 14:22, Andrew Davison wrote:

>Or maybe reentrant from the point of view of embedded goals like
>findall/bagof/setof. Maybe.

I was thinking about an application embedding trealla, spawning several
threads and running a dedicated/independent engine in each one
'pl_create()'.

Currently that is not supported for some other reasons
but eventually this would be a nice-to-have and a relatively low
hanging fruit (the g_* states/atom table can be shared,
refcounting/mutex). In some other places that needs some work to make
globals/static vars thread local.

**Comment by cehteh** [comment]
update:

im meant the
 static uint8_t s_mask1[MAX_ARITY] = {0}, s_mask2[MAX_ARITY] = {0};

to be reentrancy problematic.

for the other I'd would take as much state as possible
(but not more) out of the query structure. When states are not global
to the query in its entirety then its better to pass these state only
on the relevant parts of the code. For various reasons:
- Easier readable code, data gets close to the code that uses it.
- It unbloats the structure.
- The compiler has much better chances for optimization, a state passed
  around will reside in registers. While having it in bigger long lived
  structures it would force the compiler to emit much more load/store
  operations. (esp adding 'restrict' pointers *may* help there
  eventually)

**Comment by infradig** [comment]
pl_eval(exp) creates a query object per call.
Yes the global would need to be protected, as would modules;

**Comment by infradig** [comment]
Correct, that was a quick hack which will be revisited soon.

Some stuff is transient, like findall/bagof/setof nesting. Those
[MAX_QUEUES] arrays could be gathered into special object. But I want to
revisit creating such stuff on the heap and garbage collecting it like
streams, there's a good mechanism there.

Logtalk is talking a long time because there are actually so many logic
problems/errors that need clearing up. It's useful for that, but general
redesign issues have to wait and be thought out.

**Comment by cehteh** [comment]
On 2020-12-08 20:30, Andrew Davison wrote:

>Correct, that was a quick hack which will be revisited soon.
>
>Some stuff is transient, like findall/bagof/setof nesting. Those
>[MAX_QUEUES] arrays could be gathered into special object. But I want
>to revisit creating such stuff on the heap and garbage collecting it
>like streams, there's a good mechanism there.

Apropos memory:

1.
While going over print.c I seen there are few locations where
temporary objects are allocated, used and freed in the same function.
I clobbered a temporary allocation based on alloca (if exist) with
malloc fallback together:
https://gist.github.com/cehteh/1db1beb2b86bd6bc0126e35fd624f2be
(The idea of this comes from emacs
http://git.savannah.gnu.org/cgit/emacs.git/tree/lib/malloca.h)

Just test code so far, but I think trealla could benefit from that in
few (yet not many) places.

2.
So far my first step was to add 'ensure()' after each allocation that
may fail to abort the process in a hard way, Then I converted some of
these checks to 'may_ptr_error()' to pass errors up. This now leads to
unhandled error which eventually need to be properly addressed. But
allocation errors are nasty to handle in case the handler itself needs
to allocate memory. This needs further investigation. Ideally the
memory-hog (likely a query, its cells) needs to be cleaned and freed
before entering the handler. That should free enough resources for that.
Alternatives would be to reserve some 'emergency memory' at startup to
be used as last resort. Or (rather anyway) do hard aborts again when
not enough memory can be freed.

Eventually limits may be set with operating-system facilities
(setrlimit() etc.) This leaves the plain C99 land and needs Posix or OS
specific code. The rationale here is that allocation nowadays may
not fail by returning NULL but processes may become killed or accessing
memory that can't be mapped will raise a SIGSEGV.


>
>Logtalk is talking a long time because there are actually so many logic
>problems/errors that need clearing up. It's useful for that, but
>general redesign issues have to wait and be thought out.

Logtalk uses almost all prolog bells and whistles, no surprise thats a
really hard task.

**Comment by infradig** [comment]
All those globals/statics could be moved into the prolog object. That way
multiple threads could do pl_create().

**Comment by pmoura** [comment]
> > Logtalk is talking a long time because there are actually so many logic problems/errors that need clearing up. It's useful for that, but general redesign issues have to wait and be thought out.

> Logtalk uses almost all prolog bells and whistles, no surprise thats a really hard task.

Logtalk requires only (official and de facto) standard features. But its non trivial size helps stress test Prolog implementations.  Hopefully, we will soon be able to run all tests automated. That should simplify both exposing bugs and checking for regressions. Considering current Trealla ProLog features, we should soon be able to run +6000 of the tests bundled with Logtalk.

**Comment by cehteh** [comment]
On 2020-12-09 02:10, Paulo Moura wrote:

>> > Logtalk is talking a long time because there are actually so many
>> > logic problems/errors that need clearing up. It's useful for that,
>> > but general redesign issues have to wait and be thought out.  
>
>> Logtalk uses almost all prolog bells and whistles, no surprise thats
>> a really hard task.  
>
>Logtalk requires only (official and de facto) standard features. But
>its non trivial size helps stress test Prolog implementations.
>Hopefully, we will soon be able to run all tests automated. That
>should simplify both exposing bugs and checking for regressions.
>Considering current Trealla ProLog features, we should soon be able to
>run +6000 of the tests bundled with Logtalk.


for myself I have:

```
trealla$ cat .githooks/pre-commit
#!/bin/bash
KEEP_TESTS=5
WORKTREE_DIR="$PWD"
TEST_PREFIX=".tests-"

cd "$WORKTREE_DIR"
find -name "${TEST_PREFIX}*" -type d | sort -n | head -n -$KEEP_TESTS |
xargs -r rm -r

test_dir="${TEST_PREFIX}${GIT_AUTHOR_DATE% +*}"
git archive "$(git write-tree)" --prefix="$test_dir/" | tar xf -
cd "$test_dir"

make clean && make -j 25 debug && make test 2>&1 | tee test.log
exit $?
```

When you wan't I can commit that and send a PR. Nothing special here one
has to install (symlink) from the .git/hooks/pre-commit directory.

in other projects I also have a redneck-style desktop CI:

using https://github.com/clibs/entr and then in Makefile roughly:

ci:
  git ls-files | entr make check

This wont work well with the current Makefile since dependency tracking
and build config is a bit manual. I'll look into improving the Makefile
sometime (don't hold your breath I have some other stuff to do)

**Comment by infradig** [comment]
I have moved the updatable global static objects eg.
g_symtab/g_pool/g_modules/s_seed etc into the prolog struct.

Also g_tpl_count and a couple of others are now atomic if compiled with
-DUSE_THREADS=1 (or make THREADS=1). This means that each pl_create()
instance is now thread-safe from each other.

If I have missed any statics they will turn up in due course.

**Pull request merged**
