### PR TITLE
declaring the predicates that we want to inspected as dynamic

### PR DESCRIPTION
**Pull request by josd**
thanks to the feedback from @triska

### CODE REVIEW

**Comment by infradig** [comment]
Unfortunately things aren't that simple. Since the code does a clause/2 call on the body returned by a previous clause/2 call, you will get a permission error accessing the control structure (',')/2. What's needed, in addition, is either a functor check first, or a catch on the permission error.

**Comment by infradig** [comment]
yap -l tests/issues/test074.pl                                                                                   ±[●●][devel]
% YAP 6.5.0-3298a680 (compiled  2020-08-20T11:49:57@andrew-dell)
% database loaded from /usr/local/lib/Yap/startup.yss
clause(cup(_197451),(user:liftable(_197451),user:holds_liquid(_197451)))

          ** value access is not allowed in private_procedure (',')/2 **



:- user:main failed.

**Comment by josd** [comment]
$ gprolog --consult-file tests/issues/test074.pl
GNU Prolog 1.4.5 (64 bits)
Compiled Oct 29 2020, 23:26:09 with gcc
By Daniel Diaz
Copyright (C) 1999-2020 Daniel Diaz
compiling /home/jdroo/github.com/josd/pop/tests/issues/test074.pl for byte code...
/home/jdroo/github.com/josd/pop/tests/issues/test074.pl compiled, 99 lines read - 6829 bytes written, 10 ms
clause(cup(_40),(liftable(_40),holds_liquid(_40)))
clause(liftable(_40),(light(_40),part(_40,handle)))
clause(light(_40),small(_40))
clause(holds_liquid(_40),(part(_40,_213),concave(_213),points_up(_213)))
clause(concave(bowl),true)
cup(_40):-(small(_40),part(_40,handle)),part(_40,_213),concave(_213),points_up(_213)

**Comment by infradig** [comment]
Great. I'm putting in the permission checks now.

**Pull request merged**
