### PR TITLE
Typed cells

### PR DESCRIPTION
**Pull request by cehteh**
DO NOT MERGE YET

This is more a proposal i am working on, giving the cell unions distinctive names.
The drawback is that it clutters the code slightly more. Advantage is that its much easier to read and handle.

### CODE REVIEW

**Comment by cehteh** [comment]
Caveat, the last commit breaks 5 tests, only for review. That does a lot changes, adding all the type names.

**Comment by infradig** [comment]
I'll have a look at this soon.

**Comment by infradig** [comment]
I'd probably look at hiding the implementation details behind #defined
getters/setters for the unions.

**Comment by cehteh** [comment]
On 2020-11-16 18:15, Andrew Davison wrote:

> I'd probably look at hiding the implementation details behind #defined
> getters/setters for the unions.

Thats fine as long the code stays comprehendible. Things like a
'get_string(c)' on a float cell for example should ring bells and blink
warning lights. Imo it would be nice to have distinct types defined for
each kind of cell, I am not fan of bloated OO, but where distinct types
help its a win, hiding too much is contraproductive.

I am currently looking at the bugs the latest patch here introduced,
not found anything oblivious so far. possibly somewhere deeper is some
memory trashing. While at it i found some other problems and commit
what i have in a few minutes. Further things tomorrow.

**Comment by cehteh** [comment]
Pushed pending work. Still some segfaults on the testsuite remain.

```
$ valgrind ./tpl test009.pl
....
==1023239== Invalid read of size 1
==1023239==    at 0x15C9B8: get_char_utf8 (utf8.c:172)
==1023239==    by 0x15C89D: len_char_utf8 (utf8.c:162)
==1023239==    by 0x144CC0: list_head (parse.c:256)
==1023239==    by 0x157DA2: unify_list (runtime.c:734)
==1023239==    by 0x158312: unify_internal (runtime.c:811)
==1023239==    by 0x15769F: unify_structure (runtime.c:683)
==1023239==    by 0x158F09: match_rule (runtime.c:1048)
==1023239==    by 0x159292: run_query (runtime.c:1118)
==1023239==    by 0x1595F3: query_execute (runtime.c:1181)
==1023239==    by 0x14AC91: parser_dcg_rewrite (parse.c:1841)
==1023239==    by 0x14D8FD: parser_tokenize (parse.c:2619)
==1023239==    by 0x14EC26: module_load_text (parse.c:2945)
==1023239==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
```
I haven't found the case yet.

**Comment by cehteh** [comment]
Boiled the bug down to some minimal test-case. Can you check that? It might be that I introduced some bug, or the  dcg code relied on some stale value/faulty initialization.

**Comment by infradig** [comment]
I'll have a look.

**Comment by infradig** [comment]
Having a look at this now. A simple test:

~/cehteh/trealla >>> ./tpl
                                            ±[typed_cells]
Trealla ProLog (c) Infradig 2020, v1.2.73-445-g1f17
?- writeln("abc").
"abc"
true.
?- write_canonical("abc"),nl.
tpl: parse.c:254: list_head: Assertion `l->CSTRING.val_str' failed.
zsh: abort (core dumped)  ./tpl
~/cehteh/trealla >>>
                                           ±[typed_cells]

So i'm hoping this will be easy to track down (famous last words).

**Comment by infradig** [comment]
Change:

cell *list_tail(cell *l, cell *tmp)
{
if (!l) return NULL;
assert(tmp);

if (!is_string(l)) {
cell *h = l + 1;
return h + h->nbr_cells;
}

size_t n = len_char_utf8(l->CSTRING.val_str);

if (!n)
n = 1;

if ((l->CSTRING.len_str - n) != 0) {
tmp->val_type = TYPE_CSTRING;
tmp->flags = FLAG_BLOB|FLAG_CONST_CSTRING|FLAG_STRING;
tmp->nbr_cells = 1;
tmp->arity = 2;
tmp->CSTRING.val_str = l->CSTRING.val_str + n;
tmp->CSTRING.len_str = l->CSTRING.len_str - n;
* //tmp->LITERAL.match = NULL;*
return tmp;
}

tmp->val_type = TYPE_LITERAL;
tmp->nbr_cells = 1;
tmp->arity = 0;
tmp->flags = 0;
tmp->LITERAL.match = NULL;
tmp->LITERAL.val_off = g_nil_s;
return tmp;
}

I've left the bad line comment-out, but you can remove it.
I've also removed a redundant is_string() test I had in there.

**Comment by cehteh** [comment]
Thanks for the fix. works now.

Any final thoughts/wishes before this can be merged?

For instance a am only half happy that i used the UPPERCASE name, turns out to stick nicely to the eyes, but violates common practice.

Also the union in LITERAL should eventually be resolved, define more types like OPERATOR, RULE, BUILDIN or something like that. But this isn't a show stopper. When you are fine with that I can do the some final makeover and then its ready for merging.

**Comment by infradig** [comment]
Leave the UCASE for now. Easy search-and-replace.

I had thought briefly c->CSTRING->val-str *et al* could become
CSTRING(c)->val_str with DEBUG compile type-checking per access but
dismissed it.

Merge it in.

**Comment by cehteh** [comment]
I was thinking about some rather heavy cell_invariant_check(cell*) for debug builds. Not only checking types but also consistency, dismissed that as well, but keeping it in head if ever hardcore debugging is needed.

**Pull request closed without merging**
