### PR TITLE
Fix setup_call_cleanup/3 predicate exception for non callable setup goal

### PR DESCRIPTION
**Pull request by pmoura**
Additional tests for this and other cases have been pushed to the Logtalk git repo. With the change in this pull requests, all the tests pass.

### CODE REVIEW

**Comment by pmoura** [comment]
P.S. I tried first the simple fix of replacing the `call((S,!))` goal by `once(S)` but surprisingly that didn't work and caused several other tests for the predicate to fail.

**Comment by infradig** [comment]
Actually it would be ignore(once(S)) that's needed.

**Comment by pmoura** [comment]
> Actually it would be ignore(once(S)) that's needed.
> […](#)

Hum? No. The `setup_call_cleanup/3` is expected to fail if the setup goal fails. I pushed an additional test for this case that passes with Trealla. It's only a failure in the cleanup goal that is ignored.

**Comment by infradig** [comment]
Too early here, yes I was thinking cleanup.

**Pull request merged**
