### PR TITLE
Prolog state

### PR DESCRIPTION
**Pull request by cehteh**
Rebased and works for me now

### CODE REVIEW

**Comment by cehteh** [comment]
Halt stop .. still error, why does 'make tests' succeed but explicit call fail...

**Comment by cehteh** [comment]
Fixed the bugs, rebased it on your 'WIP' which segfaults there. Stiull should be mergeable and work when that WIP/Bug is fixed. Otherwise I do a new rebase tomorrow.

**Comment by infradig** [comment]
I stuffed up and have reverted devel. You will need to rebase. I will hold off any work untill then.

There's a lot of warning about unused return values (eg. alloc_list and append_list... they should be bool most likely now) but they can be fixed later.

**Comment by infradig** [comment]
Ha, I just realized what 'WIP' means!

**Comment by cehteh** [comment]
On 2020-12-01 23:32, Andrew Davison wrote:

>I stuffed up and have reverted devel. You will need to rebase. I will
>hold off any work untill then.

I can rebase any time no need to hold off. Maybe you open your own WIP
branch and then merge your work to devel as well or I can start to
rebase on master.

>
>There's a lot of warning about unused return values (eg. alloc_list
>and append_list... they should be bool most likely now) but they can
>be fixed later.

I intentionally added that USE_RESULT macro/-Wunused-results to force
these warnings. I will add more to that soon, eventually this becomes
the 'todo' list where returns are not handled properly and should go
away.

**Comment by infradig** [comment]
Getting an error with Logtalk. I will look into it...

~/trealla >>> ./tpl --noindex $HOME/logtalk3/integration/logtalk_tp.pl                                                ±[●][cehteh-prolog_state]
Logtalk 3.43.0-b03
Copyright (c) 1998-2020 Paulo Moura
...
Trealla ProLog (c) Infradig 2020, v1.3.4-31-gfc3a
CDEBUG FAULT INJECTION ENABLED!
?- {lgtunit(loader)}.
% [ /home/andrew/logtalk3/library/types/termp.lgt loaded ]
...
% [ /home/andrew/logtalk3/library/os/osp.lgt loaded ]
builtins.c:7938 fn_absolute_file_name_3: (tmpbuf) = ((void *)0)
% [ /home/andrew/logtalk3/library/os/os.lgt loaded ]
builtins.c:7938 fn_absolute_file_name_3: (tmpbuf) = ((void *)0)
...
% [ /home/andrew/logtalk3/tools/lgtunit/loader.lgt loaded ]
% (0 warnings)
Purge 24015 deleted rules
true.
?- 


You can install Logtalk...

   git clone https://github.com/LogtalkDotOrg/logtalk3.git

**Comment by infradig** [comment]
Things is, it actually runs ok.

**Comment by infradig** [comment]
$  ./tpl --noindex $HOME/logtalk3/integration/logtalk_tp.pl 
?- {lgtunit(loader)}.
?- {aliases(tester)}.

to reproduce.

**Comment by pmoura** [comment]
Just the `{aliases(tester)}` is enough (it loads the `lgtunit` tool; no need to load it separately.

P.S. See my feedback on the `findall/3` bug in the Logtalk issue.

**Comment by infradig** [comment]
Everything i've tested runs. So I might go with it. Then I can get on with other things.

**Comment by infradig** [comment]
> Things is, it actually runs ok.

I have fix for it now. It will be in the merge to devel.

**Comment by infradig** [comment]
> $ ./tpl --noindex $HOME/logtalk3/integration/logtalk_tp.pl
> ?- {lgtunit(loader)}.
> ?- {aliases(tester)}.
> 
> to reproduce.

There's actally more to it than just cloning & running. Anyway it's sorted now and I have merged with devel and pushed.

**Comment by cehteh** [comment]
On 2020-12-02 14:22, Andrew Davison wrote:

>Getting an error with Logtalk. I will look into it...
>
>~/trealla >>> ./tpl --noindex $HOME/logtalk3/integration/logtalk_tp.pl
>                                               ±[●][cehteh-prolog_state]
> Logtalk 3.43.0-b03
>Copyright (c) 1998-2020 Paulo Moura
>...
>Trealla ProLog (c) Infradig 2020, v1.3.4-31-gfc3a
>CDEBUG FAULT INJECTION ENABLED!
>?- {lgtunit(loader)}.
>% [ /home/andrew/logtalk3/library/types/termp.lgt loaded ]
>...
>% [ /home/andrew/logtalk3/library/os/osp.lgt loaded ]
>builtins.c:7938 fn_absolute_file_name_3: (tmpbuf) = ((void *)0)


For now I just 'dumb replaced' all malloc/ensure and returns with the
prolog_state returns. pl_error == pl_failure == 0 and added tests
with the may_*error macros where necessary. There where a lot of these
changes, it may have introduced some bugs in the process as well it may
it may reveal some bugs an problematic code which got unnoticed before.
Addressing possible problems will be the next steps.

In consequence:
- it detects errors but they are not properly handled yet (as before
  they just fall though and may eventually crash).
- Proper handling needs checks on all return values that pass errors up
(hence the USE_RESULT).
- And finally defining pl_error = negative_integer, that's
  already planned in 'internal.h'.

I've choosen this path to make a smooth transition (sans bugs). At the
'errorhandling' branch I came to points where it was hard and ugly to
pass errors back to the caller.


>% [ /home/andrew/logtalk3/library/os/os.lgt loaded ]
>builtins.c:7938 fn_absolute_file_name_3: (tmpbuf) = ((void *)0)

back to the code: 

```
if ((tmpbuf2 = realpath(tmpbuf, NULL)) == NULL) {
	if ((tmpbuf = realpath(cwd, NULL)) == NULL)
		tmpbuf = realpath(".", NULL);

	may_ptr_error(tmpbuf, free(tmpbuf));
	char *tmp = malloc(strlen(tmpbuf)+1+strlen(s)+1);
	may_ptr_error(tmp, free(tmpbuf));
	sprintf(tmp, "%s/%s", tmpbuf, s);
	free(tmpbuf);
	tmpbuf = tmp;
}

```

a) just spotted a minor bug
   `may_ptr_error(tmpbuf, free(tmpbuf));`
   doesn't need the free(tmpbuf), it is already NULL
b) `tmpbuf = realpath(".", NULL);` fails and returns NULL.
   (don't ask me why)
   without the may_ptr_error(tmpbuf) check it would crash on
   strlen(NULL).
c) instead the buffer juggling one may just extend/realloc the memory
   and concat '/', s on the go. Note that realloc(NULL, size) is valid
   and then just acts like malloc();

**Comment by infradig** [comment]
The problem is fixed, so don't worry.

**Comment by infradig** [comment]
Can we lose the USE_RESULT off these type of declarations:

static USE_RESULT prolog_state fn_iso_findall_3(query *q)


as they are only ever called through a function pointer?

**Comment by cehteh** [comment]
On 2020-12-02 17:51, Andrew Davison wrote:

>Can we lose the USE_RESULT off these type of declarations:
>
>static USE_RESULT prolog_state fn_iso_findall_3(query *q)
>
>
>as they are only ever called through a function pointer?

Possibly, I haven't thought about that. In a few cases the functions
get really called:

static USE_RESULT prolog_state fn_iso_notunify_2(query *q)
{
	return !fn_iso_unify_2(q);
}

If you want to remove the other cases mkay but I'd opt to have them
linger for some time until the dust is settled.

**Comment by infradig** [comment]
Yeah, there's only a couple of cases, but we can leave for now.

**Comment by cehteh** [comment]
On 2020-12-02 18:04, Andrew Davison wrote:

>Yeah, there's only a couple of cases, but we can leave for now.

My idea here is to make the code robust and flag problems, thus having
these around now until everything is fixed (no warnings) maybe leave
them even for future changes. Actually I am only halfway though and
will add more USE_RESULT on the go.

**Comment by infradig** [comment]
I just added one to end_list, so there you go!

**Pull request merged**
