### PR TITLE
Errorhandling

### PR DESCRIPTION
**Pull request by cehteh**
First 2 commits are some further work on errorhandlng.

To reduce the surface for errorhandling i tried to refactor the asserta/assertz code. Which shows some odd bug (commented out w/ fallback to the old code).

I haven't investigated the cause yet, but something strange is going on since factoring the shared code into a function should not break things.

I left a few comments behind to be reviewed,

### CODE REVIEW

**Comment by infradig** [comment]
I made changes to asserta/assetz in the last few hours.

**Comment by cehteh** [comment]
just push your changes i see and remerge then

**Comment by infradig** [comment]
All works fine. I have reverted out a change I made in parser_xref so
tests/tests/test073 will fail for now. I need to look at that a bit more.

**Comment by infradig** [comment]
I've made a few tweaks. I can't see why the assert_commit would hang
either. The code looks identical.

**Pull request merged**
