### PR TITLE
Add compiling with link time optimization, new sample/sudoku,pl, add extra compiler warnings

### PR DESCRIPTION
**Pull request by cehteh**
lto gives 10% speed improvement tested with the sudoku.pl

adding -Wextra shows some more warning which may be helpful to weed out problems.

### CODE REVIEW

**Comment by cehteh** [comment]
plus further work to fix the warnings generated by -Werror

**Comment by triska** [comment]
Thank you a lot for these changes! I would like to try this on OSX, however, I am running into a problem with the existing compilation (#15), is there any way to resolve this? I would greatly appreciate your help with this compilation problem.

**Comment by cehteh** [comment]
On 2020-10-27 11:44, Markus Triska wrote:

> Thank you a lot for these changes! I would like to try this on OSX,
> however, I am running into a problem with the existing compilation
> (#15), is there any way to resolve this? I would greatly appreciate
> your help with this compilation problem.

Linux here, can't help much with OSX. Glancing at your error message
at #15: why does it try to link .pl scripts? what make version is that?

I tried building with gcc, clang and tcc here, only gcc and clang
supporting lto, where gcc is the fastest. (and tcc compiled tpl being
very slow)

**Comment by infradig** [comment]
> Thank you a lot for these changes! I would like to try this on OSX, however, I am running into a problem with the existing compilation (#15), is there any way to resolve this? I would greatly appreciate your help with this compilation problem.

I'll have to make it an option.

**Comment by infradig** [comment]
Hopefully the 'make NOLDLIBS=1' will address your OSX issue. I just
realized this could be auto-detected
in the makefile for target Darwin and set.

**Comment by infradig** [comment]
Linking in the library .pl source is to make a standalone executable
possible with the library modules
available.

I wasn't familiar with -flto option!

**Comment by infradig** [comment]
Tried LTO option, I see a slowdown of about 5% when using it. Manjaro Linux system with GCC 10.2

**Comment by cehteh** [comment]
On 2020-10-27 16:47, Andrew Davison wrote:

> Tried LTO option, I see a slowdown of about 5% when using it. Manjaro
> Linux system with GCC 10.2

Interesting I have debian/stable here with gcc 8.3.0.
AMD Ryzen processor


With LTO:
$ time ./tpl -f samples/sudoku.pl >/dev/null
real	0m4,499s
user	0m4,487s
sys	0m0,010s

$ time ./tpl -g 'hanoi(1000), halt.' -f samples/hanoi.pl >/dev/null
real	0m2,425s
user	0m2,240s
sys	0m0,183s

$ time ./tpl -g 'testq, halt.' -f samples/queens11.pl 
real	0m0,901s
user	0m0,900s
sys	0m0,000s


Without:
$ time ./tpl -f samples/sudoku.pl >/dev/null
real	0m5,014s
user	0m4,982s
sys	0m0,030s

$ time ./tpl -g 'hanoi(1000), halt.' -f samples/hanoi.pl >/dev/null
real	0m2,531s
user	0m2,353s
sys	0m0,177s

$ time ./tpl -g 'testq, halt.' -f samples/queens11.pl
real	0m1,013s
user	0m1,013s
sys	0m0,000s



I admit this aren't an exhaustive tests. The hanoi does a lot I/O
printing the moves, benefiting the least.

In my experience LTO can yield quite varying results, usually things
get smaller, sometimes significantly, trealla already gets a bit
bigger. Still I would like to keep it as option which is off by
default. Eventually there should be some improvements, at least that's
what I hope for.

**Comment by cehteh** [comment]
On 2020-10-27 16:47, Andrew Davison wrote:

> Tried LTO option, I see a slowdown of about 5% when using it. Manjaro
> Linux system with GCC 10.2

Out of curiosity, I tried profile-feedback based optimization, didn't
expected much, being more surprised now:


$ make LTO=24 OPT='-fprofile-arcs'
$ make clean
$ make LTO=24 OPT='-fprofile-use'
$ time ./tpl -f samples/sudoku.pl >/dev/null
real	0m3,392s
user	0m3,380s
sys	0m0,010s

**Comment by infradig** [comment]
Now that gives me about 25%

**Comment by cehteh** [comment]
On 2020-10-27 18:26, Andrew Davison wrote:

> Now that gives me about 25%

Nice to know that there is some room for improvement :)

Note: My Goal is to have a 'embedable' prolog someday. Usable for
systems programming as rules engine. No rush here but I am planning to
add more features towards that. I will open new tickets and sending pull
requests by time.

**Comment by infradig** [comment]
Oh and there's lots of room for programmatic speed improvements. It's lost
about 30% of performance since adding features like indexing, exceptions,
attributes and others which I hope to claim back. Just a matter of finding
time. And then there's work on actual Prolog-level optimisation which is
pretty minimal for now.

**Pull request merged**
