### PR TITLE
Errorhandling

### PR DESCRIPTION
**Pull request by cehteh**
adds some debugging machinery

### CODE REVIEW

**Comment by cehteh** [comment]
Most of the things where failures can happen are now marked with ensure().
In some places not addressed yet it needs some more work/refactoring to pass errors up.

**Comment by infradig** [comment]
Probably the macros should be pulled out to a separate header that's
included by internal.h & skiplist.c and then anything anything else that
wants it.

**Comment by cehteh** [comment]
I agree, I just copied them because I wanted the decision left to you (and they are pretty small and likely wont be changed anymore)

**Comment by infradig** [comment]
Ok, i'll add them in later.

**Pull request merged**
