### PR TITLE
WIP: prolog_state returns

### PR DESCRIPTION
**Pull request by cehteh**
review of #126, work in progress, but now in a way that could be merged without turning everything upside down.

* The enum prolog_state; defines all states but pl_success as 0. This way return values are compatible with the current code. Eventually they are flipped one for another into their final values.
* Adds USE_RESULT and DISCARD_RESULT macros to detect when return values must not be ignored or still doing so. This helps a lot currently, eventually they may be removed to stay
* a lot functions (this is WIP) returning now either a pointer or prolog_state
* may_error() may_ptr_error() may_idx_error() macros for checking error conditions and returning pl_error if so.
* added a lot error handling,  returning pl_error not throwing exceptions, eventually some of these may replaced with exceptions to become catchable from prolog.
* despite having many more runtime checks now, the performance impact is minimal.
* few functions got refactored
* notably alloc_grow becomes a replacement for realloc

Short time goal is to remove the query->error (and then parser->error) flags. Passing this error state by returns.

### CODE REVIEW

**Comment by infradig** [comment]
Running tests/issues/test031.pl ...
./tests/run.sh: line 14:  5004 Segmentation fault      (core dumped) $cmd "$source" > $TMP
1d0
< f(X)

**Comment by infradig** [comment]
~/trealla >>> ./tpl -g "time(test54),halt" samples/test.pl                                                                          ±[●][devel]
builtins.c:5732 fn_sys_queuen_2: tmp failed 
zsh: abort (core dumped)  ./tpl -g "time(test54),halt" samples/test.pl
~/trealla >>>

**Comment by infradig** [comment]
Sorry, I thought this was ready, but i'm going to revert.

**Comment by cehteh** [comment]
On 2020-11-30 21:49, Andrew Davison wrote:

>Sorry, I thought this was ready, but i'm going to revert.

Was ready/worked for me (but WIP) when I opened this but I haven't
rebased on your prev. changes. will do that soon.

**Pull request merged**
